// Quranic Arabic Corpus kısaltmalarının Türkçe gramer karşılıkları.
const PART_OF_SPEECH_TR: Record<string, string> = {
  N: 'İsim',
  PN: 'Özel İsim',
  V: 'Fiil',
  ADJ: 'Sıfat',
  ADV: 'Zarf',
  PRON: 'Zamir',
  PRO: 'Zamir',
  DET: 'Tamlayıcı',
  CONJ: 'Bağlaç',
  INTJ: 'Ünlem',
  P: 'Harf-i Cer',
  PREP: 'Harf-i Cer',
  PART: 'Harf',
  REL: 'İsm-i Mevsul',
  NEG: 'Nefi Harfi',
  EMPH: 'Tekid',
  ACC: 'Harf-i Nasb',
  COND: 'Şart Edatı',
  ANS: 'Cevap Harfi',
  RES: 'Atıf',
  SUP: 'Nida / Temenni',
  INL: 'Harf-i İbtida',
  SUB: 'Harf-i Mastar',
  EXP: 'Tefsir Harfi',
  SUR: 'Taaccüb',
  EXH: 'Tahziz',
  INC: 'İbtida Harfi',
  INT: 'İstifham (Soru)',
  VOC: 'Nida (Seslenme)',
  PREV: 'Keff Harfi',
  CIRC: 'Hâl',
  COM: 'Maiyyet',
  EQ: 'Müsavat',
  REM: 'Tenbih',
  RSLT: 'Netice',
  RETRACT: 'İstidrak',
  AMD: 'İstinaf',
  AVR: 'Tahzir',
  CERT: 'Tekid',
  EXL: 'Ünlem',
  FUT: 'İstikbal',
  IMPV: 'Emir Kipi',
  LOC: 'Zarf-ı Mekân',
  T: 'Zarf-ı Zaman',
};

export function partOfSpeechTr(code: string | null | undefined): string {
  if (!code) return '—';
  return PART_OF_SPEECH_TR[code] || code;
}
