/** Arapça harfler ve Türkçe okunuş etiketleri — kök listesi harf filtresi için. */
export const ARABIC_LETTERS: { letter: string; label: string }[] = [
  { letter: 'ا', label: 'e/a' },
  { letter: 'ب', label: 'b' },
  { letter: 'ت', label: 't' },
  { letter: 'ث', label: 'se' },
  { letter: 'ج', label: 'c' },
  { letter: 'ح', label: 'ha' },
  { letter: 'خ', label: 'hı' },
  { letter: 'د', label: 'd' },
  { letter: 'ذ', label: 'zel' },
  { letter: 'ر', label: 'r' },
  { letter: 'ز', label: 'z' },
  { letter: 'س', label: 's' },
  { letter: 'ش', label: 'ş' },
  { letter: 'ص', label: 'sad' },
  { letter: 'ض', label: 'dad' },
  { letter: 'ط', label: 'tı' },
  { letter: 'ظ', label: 'zı' },
  { letter: 'ع', label: 'ayn' },
  { letter: 'غ', label: 'ğ' },
  { letter: 'ف', label: 'f' },
  { letter: 'ق', label: 'kaf' },
  { letter: 'ك', label: 'k' },
  { letter: 'ل', label: 'l' },
  { letter: 'م', label: 'm' },
  { letter: 'ن', label: 'n' },
  { letter: 'ه', label: 'h' },
  { letter: 'و', label: 'v' },
  { letter: 'ي', label: 'y' },
];
