/**
 * Kuran'da root_id'si olmayan partiküller ve özel isimler için Türkçe sözlük
 * Eşleşme lemma bazlı (trim edilerek — bazı lemmalar \r ile bitiyor)
 * Key format: "lemma|pos"
 */
module.exports = {
  // === Harf-i Cer / Edatlar (P) ===
  'و|P': 've',
  'مِن|P': '-den, -dan',
  'فِي|P': '-de, içinde',
  'ل|P': '-e, için',
  'عَلَى|P': 'üzerine, üzerinde',
  'ف|P': 've, sonra',
  'لا|P': 'hayır, değil',
  'إِلّا|P': 'ancak, başka, -den başka',
  'ب|P': 'ile, -e',
  'إِلَى|P': '-e, -a kadar',
  'ثُمّ|P': 'sonra',
  'عَن|P': '-den, hakkında',
  'لَم|P': '-medi, -madı',
  'حَتَّى|P': '-e kadar, hatta',
  'أَن|P': 'ki, -mesi',
  'قَد|P': 'muhakkak, şüphesiz',
  'أَم|P': 'yoksa, veya',
  'إِن|P': 'eğer, şüphesiz',
  'لَو|P': 'eğer, keşke',
  'هَل|P': 'mi?',
  'ك|P': 'gibi',
  'أَلا|P': 'dikkat! iyi bilin ki',
  'لَوْلا|P': 'eğer olmasaydı',
  'كَلّا|P': 'hayır! asla!',
  'لَن|P': 'asla -meyecek',
  'بَلَى|P': 'evet, elbette',
  'أَو|P': 'veya, ya da',
  'بَل|P': 'bilakis, aksine',
  'ي|P': 'benim',
  'كَأَنْ|P': 'sanki',
  'إِمّا|P': 'ya, ya da',
  'سَوْف|P': '-ecek, gelecek zaman',
  'لَمّا|P': 'henüz değil, -ince',
  'لٰكِن|P': 'fakat, ama',
  'أَمّا|P': 'fakat, -e gelince',
  'كَي|P': 'ki, -mesi için',
  'نَعَم|P': 'evet',
  'ه|P': 'onun',
  'لَيْت|P': 'keşke',
  'لٰكِنّ|P': 'fakat, lakin',
  'إِي|P': 'evet, öyledir',
  'إِلّ|P': 'ancak, başka',
  'كَلّ|P': 'hayır! asla!',
  'إِذا|P': 'ne zaman, vakit',
  'ل|P': '-e, için',
  'ِن|P': 'şüphesiz',

  // === İsim partikülleri (N) ===
  'ما|N': 'ne, şey',
  'الَّذِي|N': 'ki o, -en kimse',
  'مَن|N': 'kim, kimse',
  'إِذا|N': 'vaktaki, zaman',
  'إِذ|N': 'o vakit, hani',
  'لَمّا|N': '-dığı zaman',
  'ما|P': 'değil, hiç',
  'ماذا|N': 'ne, neden',
  'أَنَّى|N': 'nasıl, nereden',
  'أَمْس|N': 'dün',
  'هُنالِك|N': 'orada, o anda',
  'مَتَى|N': 'ne zaman',
  'كَم|N': 'kaç, nice',
  'ثَمّ|N': 'orada',
  'هُنا|N': 'burada',
  'أَيْن|N': 'nerede',
  'أَيّان|N': 'ne zaman',
  'مَهْما|N': 'her ne olursa',
  'هَيْهات|N': 'heyhat, uzak olsun',
  'وَيْ|N': 'vay, yazık',
  'كَأَيِّن|N': 'nice',
  'أ|N': 'mı?',
  'عَلَى|N': 'üst, yüksek',
  'رُب|N': 'belki, bazen',
  'لَدَى|N': 'yanında, katında',

  // === Özel isimler — Peygamberler ===
  'لُوط|N': 'Lut',
  'يُوسُف|N': 'Yusuf',
  'هارُون|N': 'Harun',
  'إِسْحاق|N': 'İshak',
  'سُلَيْمان|N': 'Süleyman',
  'داوُد|N': 'Davud',
  'يَعْقُوب|N': 'Yakub',
  'إِسْماعِيل|N': 'İsmail',
  'شُعَيْب|N': 'Şuayb',
  'زَكَرِيّا|N': 'Zekeriya',
  'أَيُّوب|N': 'Eyyub',
  'يُونُس|N': 'Yunus',
  'إِلْياس|N': 'İlyas',
  'إِدْرِيس|N': 'İdris',
  'الْيَسَع|N': 'Elyesa',
  'لُقْمان|N': 'Lokman',

  // === Özel isimler — Kavimler / Şahıslar ===
  'ثَمُود|N': 'Semud',
  'هامان|N': 'Haman',
  'قارُون|N': 'Karun',
  'إِبْلِيس|N': 'İblis',
  'إِب��لِيس|N': 'İblis',
  'جِبْرِيل|N': 'Cibril',
  'مِيكال|N': 'Mikail',
  'هارُوت|N': 'Harut',
  'مارُوت|N': 'Marut',
  'مَأْجُوج|N': 'Mecuc',
  'يَأْجُوج|N': 'Yecuc',
  'جالُوت|N': 'Calut',
  'طالُوت|N': 'Talut',
  'عِمْران|N': 'İmran',
  'عُزَيْر|N': 'Üzeyir',
  'آزَر|N': 'Azer',
  'زَيْد|N': 'Zeyd',
  'تُبَّع|N': 'Tübba',

  // === Özel isimler — Yerler ===
  'جَهَنَّم|N': 'cehennem',
  'عَدْن|N': 'Adn (cennet)',
  'سَقَر|N': 'Sakar (cehennem)',
  'لَظَى|N': 'Leza (cehennem)',
  'فِرْدَوْس|N': 'Firdevs (cennet)',
  'أَيْكَة|N': 'Eyke',
  'بابِل|N': 'Babil',
  'بَدْر|N': 'Bedir',
  'بَكَّة|N': 'Bekke (Mekke)',
  'مَكَّة|N': 'Mekke',
  'حُنَيْن|N': 'Huneyn',
  'رُوم|N': 'Rum',
  'سَيْناء|N': 'Sina',
  'سِينِين|N': 'Sinin (Sina)',
  'صَفا|N': 'Safa',
  'يَثْرِب|N': 'Yesrib (Medine)',
  'إِرَم|N': 'İrem',

  // === Özel isimler — Kitaplar / Kavramlar ===
  'تَوْراة|N': 'Tevrat',
  'إِنجِيل|N': 'İncil',
  'وَيْل|N': 'yazıklar olsun, helak',
  'إِسْتَبْرَق|N': 'ince ipek (istebrak)',
  'سُندُس|N': 'ince ipek (sündüs)',
  'تابُوت|N': 'sandık, tabut',
  'تَنُّور|N': 'tandır, fırın',
  'زَنجَبِيل|N': 'zencefil',
  'سَلْسَبِيل|N': 'Selsebil (cennet pınarı)',
  'ياقُوت|N': 'yakut',
  'يَقْطِين|N': 'kabak, asma',

  // === Özel isimler — Putlar ===
  'اللّات|N': 'Lat (put)',
  'يَعُوق|N': 'Yeuk (put)',
  'يَغُوث|N': 'Yeğus (put)',
};
